# TODO ["Di Qu" 03/08/2024] Fix build error for directory length
cc_binary(
    name = "tcp_client_poll",
    srcs = ["TCPClient_poll.cpp"],
)

cc_binary(
    name = "tcp_server_poll",
    srcs = ["TCPServer_poll.cpp"],
)