# TODO ["Di Qu" 03/08/2024] Fix build error for directory length
cc_binary(
    name = "tcp_client_select",
    srcs = ["TCPClient_select.cpp"],
)

cc_binary(
    name = "tcp_server_select",
    srcs = ["TCPServer_select.cpp"],
)